pipeline {
   agent none
   stages {
      
      stage('back-end(java)') {
         agent {
            docker { image 'maven:3.8.1-adoptopenjdk-11'}
         }
         steps {
            script {
               sh '''
                  cd backend
                  javac HelloWorld.java
                  java HelloWorld
               '''
             }
         }
      }
    
      stage('front-end(nodejs)') {
         agent {
            docker { image 'node:16-alpine' }
         }
         steps {
            script {
               sh '''
                  cd frontend
                  node hello.js
               ''' 
           }
         }
      }
   }
}
